apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [INPUT]
        Name tail
        Path /var/log/myapp.log
        Tag my_app_logs

    [OUTPUT]
        Name es
        Match **
        Host elasticsearch
        Port 9200
        Index my_app_logs
