apiVersion: v1
kind: Namespace
metadata:
  name: myapp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp1-cm
  namespace: myapp
data:
  index.html: |
    <html>
      <body>
        <h1> This is a Sample Message From MYAPP </h1> 
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: myapp
  labels:
    app: myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
           name: myapp1-cm
---
apiVersion: v1
kind: Service
metadata:
  name: myapp1-svc
  namespace: myapp
spec:
  selector:
    app: myapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort