apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-example-app
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app: my-example-app
