apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.32.96.100-172.32.96.101
  #- 192.168.0.240/28
  #- 10.1.149.240-10.1.149.250