apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-example-deploy
  labels:
    app: my-example-app
spec:
  selector:
    matchLabels:
      app: my-example-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: my-example-app
    spec:
      containers:
      - name: my-example-app
        image: nikk007/pythonapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000