apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: my-example-app
spec:
  type: NodePort
  selector:
    app: my-example-app
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 5000