apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init-script.sql: |
    CREATE DATABASE if not exists emp_db;
    USE emp_db;
    CREATE TABLE employee (
        employee_number INT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        designation VARCHAR(100) NOT NULL
    );
    INSERT INTO employee (employee_number, name, designation) VALUES
        (1, 'john', 'manager'),
        (2, 'jane', 'developer'),
        (3, 'alice', 'designer');
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: db-container
        image: mysql:5.7
        resources:
          limits:
            memory: "512Mi"
            cpu: "1500m"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: emp_db
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: db-init-script
        configMap:
          name: db-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: mydb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcache
  template:
    metadata:
      labels:
        app: memcache
    spec:
      containers:
      - name: memcache-container
        image: memcached:latest
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcache-service
spec:
  type: NodePort
  selector:
    app: memcache
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
      nodePort: 30002

