---
- name: Install Docker on EC2
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3
          - python3-pip
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == 'Debian'

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      package:
        name:
          - python3-pip
          - python3-setuptools
          - python3-wheel
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Docker
      pip:
        name: docker
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'

    - name: Install Docker Module for Python
      pip:
        name: docker

# run a sample container for testing if docker installation is working properly.
# Try to access public IP on port 81 to verify       
    - name: Start Docker container
      docker_container:
        name: my_apache_container
        image: nikk007/apachewebsite
        state: started
        ports:
          - "81:80"
