apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: nikk0007/mypython-app:latest  # Replace with your image name
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80  # The port on which the service will listen
      targetPort: 5000  # The port on which the pod listens (as specified in the Dockerfile)
  type: NodePort  # Expose the service on a random port on each Node
