version: "3"
services:
  fluentd:
    container_name: fluentd
    user: root
    image: fluent/fluentd:v1.11-debian
    volumes:
    #- /var/lib/docker/containers:/fluentd/log/containers
    - ./logs-source:/fluentd/log/containers
    - ./fluent.conf:/fluentd/etc/fluent.conf
    - ./logs-from-fluentd:/output/
    logging:
      driver: "local"